* Flex Keyword Extraction

The files in this directory are used to extract keywords out of the
Flex source code. Currently only options are extracted.

** Option Extraction

Considerations were given for multiple different ways to do this:

- =grep= the options from Flex Info documentation.
- =grep= the options out of the source code.
- Programmatically extract the options by interfacing with the source code.

The first two (using =grep=) are prone to errors which falsely
identify options. However, the /actual code/ of the /program's source/
doesn't lie. The third option interprets the options in their intended
form by running the code through a C compiler.

*** Running

Flex source code has been vendorized in this directory. We first need
the =config.h= file generated by Flex's =configure= script:

#+BEGIN_SRC bash
pushd flex-2.5.37
./configure
popd
#+END_SRC

Now build the option extraction code. This is kept in the top-level
directory so as not to "pollute" the Flex source code.
: make

Run, and voila! Options are printed to stdout.
: ./get_options
